// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	weather "sun42/weather-Beta/internal/handler/weather"
	"sun42/weather-Beta/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/weather/daily",
				Handler: weather.GetWeatherDailyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/weather/weekend",
				Handler: weather.GetWeatherWeekendHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
