// Code generated by goctl. DO NOT EDIT.
package types

type GetWeatherDailyReq struct {
	Longitude string `json:"longitude, optional"`
	Latitude  string `json:"latitude, optional"`
	City      string `json:"city, optional"`
}

type GetWeatherDailyResp struct {
	Weather interface{} `json:"weather"`
}

type GetWeatherWeekendReq struct {
	Longitude string `json:"longitude"`
	Latitude  string `json:"latitude"`
	City      string `json:"city"`
}

type GetWeatherWeekendResp struct {
	Weathers interface{} `json:"weathers"`
}
